Make annotation for `.copy()` more precise
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.copy.html
says the return value's `Object type matches caller.`

Previously, this returned a `FrameOrSeries` which was less ergonomic.
Without this fix, the newly added tests fail:

```
(venv3) aagrawal@aagrawal-mbp151 ~/src/pandas-stubs $ mypy --config-file mypy.ini third_party/3/pandas tests/snippets
tests/snippets/test_series.py:40: error: Incompatible types in assignment (expression has type "Union[DataFrame, Series]", variable has type "Series")
tests/snippets/test_frame.py:47: error: Incompatible types in assignment (expression has type "Union[DataFrame, Series]", variable has type "DataFrame")
Found 2 errors in 2 files (checked 241 source files)
```